name: Install and Test
on:
  push:
    branches: 
      - '*'
    tags-ignore:
      - v*.*.*

  pull_request:
    branches: 
      - '*'
    tags-ignore:
      - v*.*.*

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: action/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm install
          npm test
        env: 
          CI: true